# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: YOUR_PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - name: Build and Publish .NET project
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Transfer files to Compute Engine
        uses: google-github-actions/upload-to-compute-engine@v0.2
        with:
          instance_name: YOUR_INSTANCE_NAME
          zone: YOUR_INSTANCE_ZONE
          source: ./publish
          destination: /home/YOUR_USERNAME/publish

      - name: SSH into Compute Engine and run startup script
        uses: appleboy/ssh-action@v0.2.2
        with:
          host: '34.16.133.215'
          username: dohunglamk54
          key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAHriY00Q8+/oNITH1NEP9OHM5dclOoQ5nYYhgejGC7GXykj8ZW8Ih0ZNmzL6pTjTXVBGVmbCSiWi0FYv4mdpkSUmGlTZeU4G4Fwqm3UXaqcoFbPwJAOBfo9EiJv2es7bBSCxqWpZWYOgY/RrOg10uW42bdq0RJmmUak/7RcePEo4Bghy0gHju/g6v99CQPN6zLoA7wt2uVEd3XISEH7Qc1wqmdMSj1bK7uO0zcf3yZ5EEtjHSGUPJY73wRRKmD56LFt69m5B666HYSIwUnCGSThL0Mk2YY9x6hJXNqq+DX8XeCGfc+WA59gj/SoaWAp168xdMipfQVY+mTpDLNkwe3E= google-ssh {"userName":"dohunglamk54@gmail.com","expireOn":"2023-04-13T07:39:17+0000"}'
          script: |
            cd /home/YOUR_USERNAME/publish
            chmod +x startup.sh
            ./startup.sh
